davidhu2000/kube-knots

.github/workflows/docs.yaml, .github/workflows/pr-checks.yaml
adding a workflow to validate PR titles and add labels
workflows
N/A
N/A
N/A
N/A
=> chore: add semantic commit workflow to validate PR title and add labels

app/docs/package.json, app/kube-knots/package.json, package.json, yarn.lock
=> chore: update frontend depdenencies

.github/release.yml
=> chore: fix release yaml so docs show up correctly on release notes 

.github/workflows/release.yaml, app/docs/src/pages/downloads.tsx
=> docs: update downloads page with link to install docs

app/docs/src/pages/downloads.tsx
=> docs: fix macos download link

app/docs/src/pages/downloads.tsx
=> docs: fix link for download instruction in download page

app/kube-knots/src/settings/update-button.tsx
=> feat: add transition animation to update button 

app/docs/docs/features/02-overview-cluster.md, app/docs/docs/features/04-resource-creation.md, app/docs/docs/features/05-resource-actions.md, app/docs/docs/features/06-pod-logs.md, app/docs/docs/features/07-notifications.md
=> docs: fix features page title to use consistent casing

.github/dependabot.yml
to help keep gh actions up to date.
=> chore: add-gh-action-dependabot config

.github/helpers/update-gist.js, .github/release.yml, .github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml
=> chore: update release workflow to update gist and trigger docs

README.md
=> chore: add download link main readme

app/docs/docusaurus.config.js, app/docs/src/pages/downloads.tsx, app/docs/src/pages/index.tsx
=> docs: remove duplicate title on root page, improve description

app/docs/src/pages/index.tsx
=> docs: add subtitle on the root page

app/docs/src/pages/downloads.tsx
=> docs: add alt tag to download image

app/docs/src/pages/downloads.tsx
=> docs: capitalize Linux and Windows on the download page

app/kube-knots/src-tauri/Cargo.lock, app/kube-knots/src-tauri/Cargo.toml, app/kube-knots/src-tauri/src/cluster/namespaces.rs, app/kube-knots/src-tauri/src/cluster/node_metrics.rs, app/kube-knots/src-tauri/src/cluster/nodes.rs, app/kube-knots/src-tauri/src/internal/client.rs, app/kube-knots/src-tauri/src/internal/resources.rs, app/kube-knots/src-tauri/src/workloads/pod_metrics.rs, app/kube-knots/src-tauri/src/workloads/pods.rs
=> chore: add error log to all error results for better debug-ability 

package.json, patch.sh
given the monorepo setup, `npm version patch` no longer works, so built a script to automate everything. W
=> chore: create script to improve version patch process

.github/release.yml
=> chore: change release bugfix icon to bug icon

app/docs/docusaurus.config.js
=> docs: fix link typo in footer

app/docs/docusaurus.config.js
=> docs: integrate search with algolia

.github/release.yml
=> chore: update release section name for dependencies

.github/helpers/update-gist.js, .github/workflows/ci.yaml, .github/workflows/release.yaml
update macOS builds to be arch-specific, building an M1 version and an intel version
N/A
N/A
=> feat: update release job to build specific macos architecture builds

.github/workflows/docs.yaml, .github/workflows/release.yaml
=> chore: on release publish, trigger a new docs deploy

app/docs/src/pages/downloads.tsx
=> docs: update download links to account for m1/intel mac builds

.github/workflows/ci.yaml, app/docs/package.json, app/kube-knots/package.json, app/kube-knots/src/clusters/nodes.tsx, app/kube-knots/src/components/resource-table.tsx, app/kube-knots/src/hooks/use-multi-resource-list.ts, app/kube-knots/src/hooks/use-resource-list.ts, app/kube-knots/src/providers/namespaces-provider.tsx, app/kube-knots/src/root-view/metrics-overview.tsx, app/kube-knots/src/root-view/resources-overview.tsx, app/kube-knots/src/workloads/pods.tsx, package.json
=> fix: remove initial value from queries to show properly loading state

.github/workflows/release.yaml, app/kube-knots/package.json
setup some logic so all platforms runs similar code so it's easier to mantain. 
basically updated the matrix to include target for each platform.
=> chore: improve release workflow to reduce some if conditions

README.md
=> chore: add download link to main readme

app/kube-knots/src-tauri/src/configurations/mod.rs, app/kube-knots/src-tauri/src/configurations/pod_disruption_budgets.rs, app/kube-knots/src-tauri/src/main.rs, app/kube-knots/src/configurations/pod-disruption-budgets.tsx, app/kube-knots/src/hooks/use-resource-list.ts, app/kube-knots/src/router.tsx
=> feat: add pod disruption budget page

app/docs/docs/telemetry.md
=> docs: add umami faq link to telemetry doc

app/docs/src/pages/downloads.tsx
=> docs: fix installation instruction link on download page

app/docs/src/pages/downloads.tsx, app/docs/src/pages/index.tsx
=> docs: fix installation link on downloads page

app/docs/package.json, app/kube-knots/package.json, package.json, yarn.lock
=> chore(deps): update npm dependencies

app/docs/docs/installation/02-linux.md
=> docs: add linux installation documentations

.github/workflows/release.yaml, app/kube-knots/src-tauri/Cargo.lock, app/kube-knots/src-tauri/Cargo.toml, app/kube-knots/src-tauri/tauri.conf.json
allow devtools on prod builds. this make it easier to see if any issue arise. 
only enabled specific APIs in tauri config, just to get some info about the versions
=> feat: enable devtools on prod builds, tighten down API allowlist for improved security

app/kube-knots/src-tauri/Cargo.toml
forgot to update the toml file in #271
=> fix: update cargo toml dependencies to include process in allowList

app/docs/docs/contributing/_category_.json, app/docs/docs/features/_category_.json, app/docs/docs/installation/_category_.json
=> docs: add description to doc categories 

app/docs/src/pages/index.tsx
=> docs: add alt tag to app screenshot

app/docs/src/pages/index.tsx
=> docs: update main index page with h1/h2 for seo 

app/kube-knots/src/hooks/use-search.tsx
allow regex filter in resource search. 
completes #280 
it was a great idea.
=> feat: update search functionality to support regex

app/docs/docusaurus.config.js, app/docs/src/pages/downloads.tsx, app/docs/src/pages/index.tsx
still testing if umami will be a good replacement for google analytics.
=> docs: setup umami integration for doc analytics

app/kube-knots/src/components/base/table.tsx, app/kube-knots/src/components/resource-table.tsx, app/kube-knots/src/hooks/use-resource-actions.ts, app/kube-knots/src/hooks/use-resource-list.ts
=> chore: optimize rendering on table, prevent table rerender if overlay exists

app/kube-knots/src/components/resource-trigger-modal.tsx
#288 fixed create resource, but broke cronjob trigger. This will allow trigger to work again.
=> fix: fix create_job argument on cronjob trigger

app/docs/src/pages/downloads.tsx, app/docs/src/pages/index.tsx, app/kube-knots/src/telemetry.ts
from umami discord. checked the function in console, it did change.
=> fix: update umami function to fix app version telemetry

app/kube-knots/src/clusters/events.tsx, app/kube-knots/src/components/resource-table.tsx
just hardcoded sorting events by last seen for now. still need to build it sorting functionality into the table
=> feat: add functionality to sort events by last seen
